# Generated by Django 3.2.5 on 2023-01-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNT', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
