# Generated by Django 3.2.5 on 2023-01-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financeledgerlist',
            fields=[
                ('stddate', models.DateField(db_column='stdDate', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('seq', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('memo', models.CharField(blank=True, max_length=50, null=True)),
                ('paytype', models.IntegerField(db_column='payType')),
                ('createdate', models.DateTimeField(db_column='createDate')),
                ('updatedate', models.DateTimeField(db_column='updateDate')),
            ],
            options={
                'db_table': 'financeledgerlist',
                'managed': False,
            },
        ),
    ]
