# Generated by Django 3.2.5 on 2023-01-04 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financeledgerlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stddate', models.DateField(db_column='stdDate')),
                ('email', models.CharField(max_length=50)),
                ('seq', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('paytype', models.IntegerField(db_column='payType', default=0)),
            ],
            options={
                'db_table': 'financeledgerlist',
                'unique_together': {('stddate', 'email', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='Financeledgerdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, db_column='createDate')),
                ('updatedate', models.DateTimeField(auto_now=True, db_column='updateDate')),
                ('financeledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='FINANCELEDGER.financeledgerlist')),
            ],
            options={
                'db_table': 'financeledgerdetail',
            },
        ),
    ]
