# Generated by Django 3.2.5 on 2023-01-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FINANCELEDGER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeledgerdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, db_column='createDate')),
                ('updatedate', models.DateTimeField(auto_now=True, db_column='updateDate')),
            ],
            options={
                'db_table': 'financeledgerdetail',
                'managed': False,
            },
        ),
    ]
